spring.application.name=CodeCompare
server.port=8080
logging.level.tech.adivaste.CodeCompare=INFO
logging.level.org.springframework.web=INFO

# Repository configuration
codecompare.repo.base-path=./repositories

# SFDX configuration
codecompare.sfdx.timeout=300000
codecompare.sfdx.max-retries=3
